ToTheLast46.Web/Areas/Admin666/Controllers/FriendsController.cs
using Nightjar.ToTheLast.DAL;
using Nightjar.ToTheLast.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToTheLast46.Web.Areas.Admin666.Models;

namespace ToTheLast46.Web.Areas.Admin666.Controllers
{
    //[Authorize]
    public class FriendsController : Controller
    {
        // GET: Admin/Friends
        public ActionResult Index()
        {
            ILinkDAC dac = new LinkDAC();
            int totalNoRecords, startIndex = 0;
            IList<Link> links = dac.Get(null, "SortOrder ASC", startIndex, Int32.MaxValue, out totalNoRecords);
            return View(links);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(LinkCreate link)
        {
            if (!ModelState.IsValid)
                return View(link);

            ILinkDAC dac = new LinkDAC();
            dac.Add(link.URL, link.Title, link.Note, link.SortOrder);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ILinkDAC dac = new LinkDAC();
            var link = dac.Get(id);
            var model = new LinkEdit { LinkID = link.LinkID, SortOrder = link.SortOrder, Note = link.Note, Title = link.Title, URL = link.URL };
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(LinkEdit link)
        {
            if (!ModelState.IsValid)
                return View(link);
            ILinkDAC dac = new LinkDAC();
            dac.Update(link.LinkID, link.URL, link.Title, link.Note, link.SortOrder);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            ILinkDAC dac = new LinkDAC();
            dac.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

ToTheLast46.Web/Areas/Admin666/Controllers/GalleryController.cs
using Nightjar.ToTheLast.DAL;
using Nightjar.ToTheLast.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToTheLast46.Web.Areas.Admin666.Models;

namespace ToTheLast46.Web.Areas.Admin666.Controllers
{
    //[Authorize]
    public class GalleryController : Controller
    {
        // GET: Admin/Gallery
        public ActionResult Index()
        {
            IGalleryDAC dac = new GalleryDAC();
            IList<Gallery> galleries = dac.Get();
            return View(galleries);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(GalleryCreate gallery)
        {
            if (!ModelState.IsValid)
                return View(gallery);

            IGalleryDAC dac = new GalleryDAC();
            dac.Add(gallery.Name, gallery.Description, gallery.SortOrder);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            IGalleryDAC dac = new GalleryDAC();
            var gallery = dac.GetGallery(id);
            var model = new GalleryEdit { Description = gallery.Description, GalleryID = gallery.GalleryID, Name = gallery.Name, SortOrder = gallery.SortOrder, MainImage = gallery.DisplayImage };
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(GalleryEdit gallery)
        {
            if (!ModelState.IsValid)
                return View(gallery);
            IGalleryDAC dac = new GalleryDAC();
            dac.Update(gallery.GalleryID, gallery.Name, gallery.Description, gallery.SortOrder, gallery.MainImage);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            IGalleryDAC dac = new GalleryDAC();
            dac.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

ToTheLast46.Web/Areas/Admin666/Controllers/GigsController.cs
using Nightjar.ToTheLast.DAL;
using Nightjar.ToTheLast.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToTheLast46.Web.Areas.Admin666.Models;

namespace ToTheLast46.Web.Areas.Admin666.Controllers
{
    //[Authorize]
    public class GigsController : Controller
    {
        // GET: Admin/Gigs
        public ActionResult Index()
        {
            IGigDAC dac = new GigDAC();
            int totalNoRecords;

            //upcoming gigs
            int startIndex = 0;
            IList<Gig> upcomingGigs = dac.Get("StartDateTime>=DATE()", "StartDateTime ASC", startIndex, Int32.MaxValue, out totalNoRecords);
            return View(upcomingGigs);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(GigCreate gig)
        {
            if (!ModelState.IsValid)
                return View(gig);

            IGigDAC dac = new GigDAC();
            dac.Add(gig.Description, gig.Venue, gig.Date);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            IGigDAC dac = new GigDAC();
            var gig = dac.Get(id);
            var model = new GigEdit { Date = gig.StartDateTime, Description = gig.Description, GigID = gig.GigID, Venue = gig.Venue };
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(GigEdit gig)
        {
            if (!ModelState.IsValid)
                return View(gig);
            IGigDAC dac = new GigDAC();
            dac.Update(gig.GigID, gig.Description, gig.Venue, gig.Date);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            IGigDAC dac = new GigDAC();
            dac.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

ToTheLast46.Web/Areas/Admin666/Controllers/GuestbookController.cs
using Nightjar.ToTheLast.DAL;
using Nightjar.ToTheLast.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToTheLast46.Web.Areas.Admin666.Models;

namespace ToTheLast46.Web.Areas.Admin666.Controllers
{
    //[Authorize]
    public class GuestbookController : Controller
    {
        // GET: Admin/Guestbook
        public ActionResult Index(int pageNo = 1, int pageSize = 10)
        {
            IGuestbookDAC dac = new GuestbookDAC();
            int totalNoRecords;
            int startIndex = pageSize * (pageNo - 1);
            IList<Guestbook> guestbooks = dac.Get(null, "DateCreated DESC", startIndex, pageSize, out totalNoRecords);
            return View(guestbooks);
        }

        public ActionResult Edit(int id)
        {
            IGuestbookDAC dac = new GuestbookDAC();
            var guestbook = dac.Get(id);
            var model = new GuestbookEdit { Comment=guestbook.Comment,Date=guestbook.DateCreated,Display=guestbook.Display,GuestbookID=guestbook.GuestbookID,Name=guestbook.Name,Reply=guestbook.Reply };
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(GuestbookEdit guestbook)
        {
            if (!ModelState.IsValid)
                return View(guestbook);
            IGuestbookDAC dac = new GuestbookDAC();
            dac.Update(guestbook.GuestbookID,guestbook.Display);
            dac.Update(guestbook.GuestbookID, guestbook.Reply);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            IGuestbookDAC dac = new GuestbookDAC();
            dac.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

ToTheLast46.Web/Controllers/HomeController.cs
using Nightjar.ToTheLast.DAL;
using Nightjar.ToTheLast.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToTheLast46.Web.Models;

namespace ToTheLast46.Web.Controllers
{
    public class HomeController : Controller
    {
        IGuestbookDAC _guestbookDAC;

        public HomeController()
        {
            _guestbookDAC = new GuestbookDAC();
        }
        public ActionResult Index()
        {
            ViewBag.Content = System.IO.File.ReadAllText(Server.MapPath(@"~\App_Data\default.aspx.htm"));
            return View();
        }

        public ActionResult Band()
        {
            IProfileDAC dac = new ProfileDAC();
            IList<Profile> profiles = dac.GetAll();
            return View(profiles);
        }

        public ActionResult Blog(int pageNo = 1, int pageSize = 6)
        {
            INewsDAC dac = new NewsDAC();
            int totalNoRecords;
            int startIndex = pageSize * (pageNo - 1);
            var news = dac.Get(null, "DateCreated DESC", startIndex, pageSize, out totalNoRecords);
            return View(news);
        }

        public ActionResult Gigs()
        {
            IGigDAC dac = new GigDAC();
            int totalNoRecords;

            //upcoming gigs
            int startIndex = 0;
            IList<Gig> upcomingGigs = dac.Get("StartDateTime>=DATE()", "StartDateTime ASC", startIndex, Int32.MaxValue, out totalNoRecords);
            return View(upcomingGigs);
        }

        public ActionResult Guestbook(int pageNo = 1, int pageSize = 10)
        {
            IGuestbookDAC dac = new GuestbookDAC();
            int totalNoRecords;
            int startIndex = pageSize * (pageNo - 1);
            IList<Guestbook> guestbooks = dac.Get("Display=Yes", "DateCreated DESC", startIndex, pageSize, out totalNoRecords);
            return View(guestbooks);
        }

        public ActionResult AddComment()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddComment(GuestbookComment comment)
        {
            if (!ModelState.IsValid)
                return View(comment);

            _guestbookDAC.Add(comment.Name, comment.Email, comment.Com);
            TempData["Success"] = true;
            return RedirectToAction("AddComment");

        }

        public ActionResult Gallery()
        {
            IGalleryDAC dac = new GalleryDAC();
            IList<Gallery> galleries = dac.Get();
            return View(galleries);
        }

        public ActionResult GalleryImages(int id)
        {
            IGalleryDAC dac = new GalleryDAC();
            Gallery gallery = dac.GetGallery(id);
            ViewBag.GalleryTitle = gallery.Name;
            IImageDAC imageDAC = new ImageDAC();
            var images = imageDAC.Get(id);
            return View(images);
        }

        public ActionResult Friends()
        {
            ILinkDAC dac = new LinkDAC();
            int totalNoRecords, startIndex = 0;
            IList<Link> links = dac.Get(null, "SortOrder ASC", startIndex, Int32.MaxValue, out totalNoRecords);
            return View(links);
        }
    }
}

ToTheLast46.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ToTheLast46.Web/Views/Home/AddComment.cshtml
@model ToTheLast46.Web.Models.GuestbookComment

@{
    ViewBag.Title = "Add Comment to Guestbook";
}

<h2>Add Comment to Guestbook</h2>
@if (TempData["Success"] != null)
{
    <p>Thank you. Your comment has been saved. It will appear on the website shortly</p>
}
else
{

    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Com, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Com, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Com, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Add Comment" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
}

<div>
    @Html.ActionLink("Back to Guestbook", "Guestbook")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToTheLast46.Web/Views/Home/Band.cshtml
@model IList<Nightjar.ToTheLast.Entities.Profile>
@{
    ViewBag.Title = "The Band";
}

<h2>The Band</h2>
@{var imageFloat = "right"; var rnd = new Random((int)DateTime.Now.Ticks); }
@foreach (var item in Model)
{
    <div class="band-member" style="padding-bottom:1em;">
        <h3>@item.Name</h3><a name="@item.Name.ToString().Replace(" ","-")"></a>
        <div>
            @if (item.ImageExists)
            {
                var degree = string.Format("{0}deg", (rnd.Next(-3, 3)));
                <img src="/sitecontent/images/band/@item.ImageName" style="float:@imageFloat;max-height:300px;margin:0 15px;box-shadow: 1px 1px 15px #000;transform: rotateZ(@degree);" />
            }
            @Html.Raw(item.ProfileText)
        </div>
        <div style="clear:both;"></div>
    </div>
    imageFloat = imageFloat == "right" ? "left" : "right";
}

ToTheLast46.Web/Views/Home/Blog.cshtml
@model IEnumerable<Nightjar.ToTheLast.Entities.News>

@{
    ViewBag.Title = "News";
}

<h2>Blog</h2>

<table class="table">


    @foreach (var item in Model)
    {
        <tr>

            <td>
                <h3>
                    @Html.DisplayFor(modelItem => item.Subject)
                </h3>
                @Html.DisplayFor(modelItem => item.NewsText)
                <p style="text-align:right;font-style:italic;">@Html.DisplayFor(modelItem => item.DateCreated)</p>
            </td>
        </tr>
    }

</table>

ToTheLast46.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ToTheLast46.Web/Views/Home/Friends.cshtml
@model IEnumerable<Nightjar.ToTheLast.Entities.Link>

@{
    ViewBag.Title = "Friends";
}

<h2>Friends</h2>

<table class="table">

    @foreach (var item in Model.OrderBy(f => f.SortOrder))
    {
        <tr>
            <td>
                <div><a href="@Html.DisplayFor(modelItem => item.URL)">@Html.DisplayFor(modelItem => item.Title)</a></div>
                @Html.DisplayFor(modelItem => item.Note)
            </td>
        </tr>
    }

</table>

ToTheLast46.Web/Views/Home/Gallery.cshtml
@model IEnumerable<Nightjar.ToTheLast.Entities.Gallery>

@{
    ViewBag.Title = "Gallery";
}

<h2>Gallery</h2>

<table class="table">


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (!string.IsNullOrEmpty(item.DisplayImage))
                {
                    <a href="@Url.Action("GalleryImages", new {id=item.GalleryID })"><img src="/sitecontent/images/gallery/@item.DisplayImage" style="box-shadow: 1px 1px 7px #000;max-height:200px;" /></a>
                }
            </td>
            <td>
                <h3>@Html.DisplayFor(modelItem => item.Name)</h3>
                <p><em>@Html.DisplayFor(modelItem => item.Description)</em></p>
                <p><a href="@Url.Action("GalleryImages", new {id=item.GalleryID })">View all images</a></p>
            </td>
        </tr>
    }

</table>

ToTheLast46.Web/Views/Home/GalleryImages.cshtml
@model IEnumerable<Nightjar.ToTheLast.Entities.Image>

@{
    ViewBag.Title = ViewBag.GalleryTitle;
}

@section styles{

    <link href="~/Content/jquery.fancybox.css?v=2.1.5" rel="stylesheet" />
}

<h2>@ViewBag.GalleryTitle</h2>



@foreach (var item in Model)
{
    <a class="fancybox" rel="group" href="~/SiteContent/Images/Gallery/@item.Filename">
        <img src="~/SiteContent/Images/Gallery/@item.Filename" alt="@item.Title" style="max-height:100px; margin:5px;box-shadow: 1px 1px 7px #000;" />
    </a>

}

@section scripts{
    <script src="~/Scripts/jquery.fancybox.pack.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(".fancybox").fancybox();
        });
    </script>
}

ToTheLast46.Web/Views/Home/Gigs.cshtml
@model IEnumerable<Nightjar.ToTheLast.Entities.Gig>

@{
    ViewBag.Title = "Gigs";
}

<h2>Gigs</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StartDateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Venue)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StartDateTime)
            </td>
            <td>
                <h4>@Html.DisplayFor(modelItem => item.Venue)</h4>
                <p><em>@Html.DisplayFor(modelItem => item.Description)</em></p>
            </td>
        </tr>
    }

</table>

ToTheLast46.Web/Views/Home/Guestbook.cshtml
@model IEnumerable<Nightjar.ToTheLast.Entities.Guestbook>

@{
    ViewBag.Title = "Guestbook";
}

<h2>Guestbook</h2>

<p style="float:right;">
    @Html.ActionLink("Add Comment", "AddComment")
</p>
<table class="table">

    @foreach (var item in Model)
    {
        if (item.Display)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Comment)
                    <p style="margin-top:1em;color:lightslategrey"><em>@Html.DisplayFor(modelItem => item.Reply)</em></p>
                </td>
                <td></td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>
            </tr>
        }
    }

</table>

ToTheLast46.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "To The Last";
    var content = (string)ViewBag.Content;
}
@section styles{
    <style>
        .body-content
        {
            font-size:110%;
        }
        .body-content img
        {
            max-height:200px;margin:0 20px;box-shadow: 1px 1px 15px #000;
        }

    </style>
    }

<div class="row" style="margin-top:1em;">
    <div class="col-md-12">
        <p>
            <img style="float:right;transform: rotateZ(3deg);" src="/SiteContent/Images/Gallery/To%20The%20Last%20Brickies%20May%205th.jpg16%20%28Medium%29.jpg" />
            @Html.Raw(content.Substring(0,content.IndexOf("</p>")+4))
            <img style="float:left;transform: rotateZ(-1deg);" src="/SiteContent/Images/Gallery/Rick's%20phone%201269.jpg" />
            @Html.Raw(content.Substring(content.IndexOf("</p>")+4))
        </p>
    </div>
</div>