ToTheLast46.Web/Areas/Admin666/Controllers/ImageController.cs
using Nightjar.ToTheLast.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToTheLast46.Web.Areas.Admin666.Models;

namespace ToTheLast46.Web.Areas.Admin666.Controllers
{
    //[Authorize]
    public class ImageController : Controller
    {
        // GET: Admin666/Image
        public ActionResult Index(int galleryID)
        {
            IImageDAC dac = new ImageDAC();
            IGalleryDAC galleryDAC = new GalleryDAC();
            var gallery = galleryDAC.GetGallery(galleryID);
            ViewBag.Gallery = gallery.Name;
            ViewBag.GalleryID = gallery.GalleryID;
            ViewBag.DefaultImage = gallery.DisplayImage;
            var images = dac.Get(galleryID);
            return View(images);
        }

        public ActionResult Create(int galleryID)
        {
            var model = new ImageCreate { GalleryID = galleryID };
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase file, ImageCreate image)
        {
            if (file == null)
                ModelState.AddModelError("Filename", "Please select an image");
            else
                image.Filename = file.FileName;

            if (!ModelState.IsValid)
                return View(image);

            string path = System.IO.Path.Combine(Server.MapPath("~/SiteContent/Images/Gallery/"), image.Filename);
            file.SaveAs(path);

            IImageDAC dac = new ImageDAC();
            dac.Add(image.Filename, image.Title, image.GalleryID, 1);
            return RedirectToAction("Index", new { galleryID = image.GalleryID });
        }

        public ActionResult Edit(int id)
        {
            IImageDAC dac = new ImageDAC();
            var image = dac.GetImage(id);
            var model = new ImageEdit { Filename = image.Filename, GalleryID = image.GalleryID, Title = image.Title, ImageID = image.ImageID };
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ImageEdit image)
        {
            if (!ModelState.IsValid)
                return View(image);
            IImageDAC dac = new ImageDAC();
            dac.Update(image.ImageID, image.Title, 1);
            return RedirectToAction("Index", new { galleryID = image.GalleryID });
        }

        [HttpPost]
        public ActionResult Delete(int id, int galleryID)
        {
            IImageDAC dac = new ImageDAC();
            dac.Delete(id);
            return RedirectToAction("Index", new { galleryID = galleryID });
        }

        [HttpPost]
        public ActionResult UpdateDefaultImage(int galleryID,string image)
        {
            IGalleryDAC galleryDAC = new GalleryDAC();
            galleryDAC.SetDisplayImage(galleryID, image);
            return Json(new { Success = true });
        }
    }
}

ToTheLast46.Web/Areas/Admin666/Views/Image/Create.cshtml
@model ToTheLast46.Web.Areas.Admin666.Models.ImageCreate

@{
    ViewBag.Title = "Create";
}

<h2>Add Image</h2>


@using (Html.BeginForm("Create", "Image", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GalleryID)
        <div class="form-group">
            @Html.LabelFor(model => model.Filename, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div>
                    <span class="btn btn-default btn-file">
                        Browse <input type="file" name="file">
                    </span>
                    <span class="image-name"></span>
                </div>               

                @Html.ValidationMessageFor(model => model.Filename, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { galleryID = Model.GalleryID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $(document).on('change', '.btn-file :file', function () {
                var input = $(this),
                    numFiles = input.get(0).files ? input.get(0).files.length : 1,
                    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                input.trigger('fileselect', [numFiles, label]);
            });

            $('.btn-file :file').on('fileselect', function (event, numFiles, label) {
                $(".image-name").text(label);
            });
        });
    </script>
}

ToTheLast46.Web/Areas/Admin666/Views/Image/Edit.cshtml
@model ToTheLast46.Web.Areas.Admin666.Models.ImageEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Image</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ImageID)
        @Html.HiddenFor(model => model.Filename)
        @Html.HiddenFor(model => model.GalleryID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { galleryID = Model.GalleryID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToTheLast46.Web/Areas/Admin666/Views/Image/Index.cshtml
@model IEnumerable<Nightjar.ToTheLast.Entities.Image>

@{
    ViewBag.Title = "Index";
}

<h2>Images for the @ViewBag.Gallery</h2>

<p>
    @Html.ActionLink("Add New", "Create", new { galleryID = ViewBag.GalleryID })
</p>
@if (Model.Count() > 0 && ViewBag.DefaultImage == null)
{
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <strong>Select an image for the Gallery page using the radio buttons next to the image</strong>
    </div>
}
<table class="table">
    <tr>
        <th></th>
        <th>
            Image
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td><input type="radio" name="defaultImage" value="@item.Filename" checked="@(ViewBag.DefaultImage==item.Filename?"checked":(string)null)" class="defaultImage" /></td>
            <td>
                <img style="height:100px;" src="~/SiteContent/Images/Gallery/@item.Filename" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ImageID }) |
                <form method="post" action="@Url.Action("Delete")" style="display:inline;">
                    <input type="hidden" value="@item.ImageID" name="id" />
                    <input type="hidden" value="@item.GalleryID" name="galleryID" />
                    <a href="#" class="delete-btn">Delete</a>
                </form>
            </td>
        </tr>
    }

</table>

@section scripts
{
    <script>
        $(document).ready(function () {

            $(".delete-btn").click(function (e) {
                var frm = $(this).closest("form");
                e.preventDefault();
                bootbox.confirm("Are you sure?", function (result) {
                    if (result) {
                        frm.submit();
                    }
                });
            });

            $(".defaultImage").click(function (e) {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("UpdateDefaultImage")",
                    data: {image:$(this).val(),galleryID:@ViewBag.GalleryID},
                    dataType: "json",
                    success: function (response) {
                        $(".alert").slideUp();
                    }
                });

            });
        });
    </script>
}