ToTheLast46.Web/Areas/Admin666/Controllers/ProfilesController.cs
using Nightjar.ToTheLast.DAL;
using Nightjar.ToTheLast.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToTheLast46.Web.Areas.Admin666.Models;

namespace ToTheLast46.Web.Areas.Admin666.Controllers
{
    //[Authorize]
    public class ProfilesController : Controller
    {
        // GET: Admin/Profiles
        public ActionResult Index()
        {
            IProfileDAC dac = new ProfileDAC();
            IList<Profile> profiles = dac.GetAll();
            return View(profiles);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(ProfileCreate profile)
        {
            if (!ModelState.IsValid)
                return View(profile);

            IProfileDAC dac = new ProfileDAC();
            dac.Add(profile.Name, profile.ProfileText, profile.SortOrder);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            IProfileDAC dac = new ProfileDAC();
            var profile = dac.GetProfile(id);
            var model = new ProfileEdit { ProfileID = profile.ProfileID, Name = profile.Name, ProfileText = profile.ProfileText, SortOrder = profile.SortOrder };
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(ProfileEdit profile)
        {
            if (!ModelState.IsValid)
                return View(profile);
            IProfileDAC dac = new ProfileDAC();
            dac.Update(profile.ProfileID, profile.Name, profile.ProfileText, profile.SortOrder);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            IProfileDAC dac = new ProfileDAC();
            dac.Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult AddImage(HttpPostedFileBase file, int profileID)
        {
            if (file != null)
            {
                IProfileDAC dac = new ProfileDAC();
                var profile = dac.GetProfile(profileID);
                string path = System.IO.Path.Combine(Server.MapPath("~/SiteContent/Images/Band/"), profile.ImageName);
                file.SaveAs(path);
            }
            // after successfully uploading redirect the user
            return RedirectToAction("Index");
        }
    }
}

ToTheLast46.Web/Areas/Admin666/Views/Profiles/Create.cshtml
@model ToTheLast46.Web.Areas.Admin666.Models.ProfileCreate

@{
    ViewBag.Title = "Create Profile";
}

<h2>Create Profile</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfileText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="ProfileText">@(Model?.ProfileText)</textarea>
                @Html.ValidationMessageFor(model => model.ProfileText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SortOrder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SortOrder, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SortOrder, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
}

ToTheLast46.Web/Areas/Admin666/Views/Profiles/Edit.cshtml
@model ToTheLast46.Web.Areas.Admin666.Models.ProfileEdit

@{
    ViewBag.Title = "Edit Profil";
}

<h2>Edit Profile</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProfileID)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfileText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="ProfileText">@(Model?.ProfileText)</textarea>
                @Html.ValidationMessageFor(model => model.ProfileText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SortOrder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SortOrder, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SortOrder, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
}

ToTheLast46.Web/Areas/Admin666/Views/Profiles/Index.cshtml
@model IEnumerable<Nightjar.ToTheLast.Entities.Profile>

@{
    ViewBag.Title = "The Band";
}
@section styles
{
    <style>
        .image-upload-container { margin: 1em 0; }
        .table tr td:nth-child(5){width:7em;}
    </style>
}

<h2>The Band</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Image
        </th>
        <th>
            Name
        </th>
        <th>
            Text
        </th>
        <th>
            Order
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @using (Html.BeginForm("AddImage", "Profiles", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    if (item.ImageExists)
                    {
                        <img style="height:200px;" alt="@item.ImageName" src="~/SiteContent/Images/Band/@item.ImageName" />
                        <div style="margin:1em 0;">
                            <label for="file">Change Image</label>
                            <span class="btn btn-default btn-file">
                                Browse <input type="file" name="file">
                            </span>
                        </div>
                    }
                    else
                    {
                        <div>
                            <label for="file">Add Image</label>
                            <span class="btn btn-default btn-file">
                                Browse <input type="file" name="file">
                            </span>
                        </div>
                    }

                    <input type="hidden" name="profileID" value="@item.ProfileID" />
                    <div class="image-upload-container" style="display:none;">
                        <span class="image-name"></span>
                        <input type="submit" value="Upload" class="btn btn-primary" />
                    </div>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.Raw(item.ProfileText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SortOrder)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ProfileID }) |
                <form method="post" action="@Url.Action("Delete")" style="display:inline;">
                    <input type="hidden" value="@item.ProfileID" name="id" />
                    <a href="#" class="delete-btn">Delete</a>
                </form>
            </td>
        </tr>
    }

</table>

@section scripts
{
    <script>
        $(document).ready(function () {
            $(document).on('change', '.btn-file :file', function () {
                var input = $(this),
                    numFiles = input.get(0).files ? input.get(0).files.length : 1,
                    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                input.trigger('fileselect', [numFiles, label]);
            });

            $('.btn-file :file').on('fileselect', function (event, numFiles, label) {
                var td = $(this).closest("td");
                td.find(".image-upload-container").slideDown();
                td.find(".image-name").text(label);
            });

            $(".delete-btn").click(function (e) {
                var frm = $(this).closest("form");
                e.preventDefault();
                bootbox.confirm("Are you sure?", function (result) {
                    if (result) {
                        frm.submit();
                    }
                });
            });
        });
    </script>
}